name: tests

on:
  # Trigger the workflow on push or pull request on main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run cron job every month, https://crontab.guru/every-month
    - cron: '0 0 1 * *'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # This job tests that the CC works
  test-cc-and-jb-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # currently not testing on windows
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # Use the default CC
    - name: Check black style
      run: |
        black ./ --check
    # Run tests
    - name: Pytest tests
      run: |
        pytest
    # Build the example book
    - name: Build default book
      run: |
        cookiecutter . --no-input --overwrite-if-exists
        pip install -r my_book/requirements.txt
        jupyter-book build .
    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "_build/html"